### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by benwilson512** [ex-aws/ex_aws_route53#1]
Hey @kagux, per https://elixirforum.com/t/proposal-exaws-2-0/9269 the ExAws project is splitting out each service into its own project.

You are the original contributor the Route53 service to ExAws. If you wish to be its maintainer, please let me know and I will give you commit access to this repository. If you do not want this, let me know and I will look for someone else.

Thank you!

**Comment by kagux** [comment]
Hey @benwilson512,

Sure, I don't mind maintaining this package! 

As I understand, it doesn't require any immediate changes, right?

**Comment by benwilson512** [comment]
Thank you! And yes that is correct, there are no outstanding issues.
