### ISSUE TITLE
Please include most recent commit in release

### ISSUE THREAD

**Issue by muse** [ex-aws/ex_aws_route53#5]
As of right now using the most recent version (2.0.1) the name space is broken due to a commit which hasn't been added to a release yet (d6b486fbbbf92715c419c2b7735836ccfe069d5c). Please add this to an official release so I can reference a version in my `mix.exs` rather than the repository itself.

**Comment by kagux** [comment]
@benwilson512 can you help with this?

**Comment by benwilson512** [comment]
hey @kagux can you send me your email address? I want to add you as a maintainer on hex so that you can handle doing releases yourself.

**Comment by kagux** [comment]
@benwilson512 it's kaguxmail [at] gmail.com

**Comment by benwilson512** [comment]
Done, you should be able to publish.

**Comment by kagux** [comment]
perfect! released

**Comment by benwilson512** [comment]
Thank you!

**Comment by muse** [comment]
Thanks a lot :)
